name: Publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.24.3"
      - name: Build
        run: |
          go build
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v6
        with:
          tags: teranovalp/http-catch-all:${{ env.CI_REF_NAME }}
          push: true
          context: .
      - uses: docker/build-push-action@v6
        with:
          tags: teranovalp/http-catch-all:latest
          push: true
          context: .
      - uses: actions/upload-artifact@4
        with:
          path: ./dist/
          retention-days: 3
