name: Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./dockerfile
          failure-threshold: warning
      - uses: actions/setup-go@v5
      - name: Build
        run: |
          go build
